kind: Macros
metadata:
  namespace: Kubernetes
spec:
  - name: "ReplicasSizeMacro"
    description: "Replicas size for the deployment"
    parameters:
      replicasSize: 1
    processor:
      - type: patch
        description: "Changing replicas to 3 and setting resource limits"
        phase: POST_FLIGHT
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/replicas"
              value: 2
