kind: Rules
metadata:
  namespace: Kubernetes-Demo
spec:
  - name: "k8s.AddFreemarkerJsonPathLabels"
    description: "Add a stitch label to a resource"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment'"
    processor:
      - type: freemarker
        description: "Adding label to kubernetes spec using jsonpath"
        merge:
          type: jsonpath
          path: "$.metadata.labels"
        parameters:
          template: |
            {
              "environment": "#ctx.currentDeployedApplication.environment.name"
            }
