# kind: Rules
# metadata:
#   namespace: Kubernetes
# spec:
#   - name: "AddLabels"
#     condition:
#       deployedType: k8s.Resources
#     processor:
#       - type: "k8s:AddLabelsMacro"
#         description: "Add labels macro"
#         phase: PATCH
#         parameters:
#           labels: "{\
#               \"scope\": \"#{@environment.nameContains('prod') ? 'production' : 'nonprod'}\",\
#               \"environment\": \"#{@environment.name}\",\
#               \"service\": \"k8s-stitch\"\
#             }"
