kind: Rules
metadata:
  namespace: k8s-freemarker-template
spec:
  - name: "k8s.AddFreemarkerLabels"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment'"
    processor:
      - type: k8s.MacroFreemarkerAddLabels
        description: "Adding freemarker macro"
        weight: 10
        parameters:
          application: "#ctx.getCurrentDeployedApplication().getName()"
          environment: "#ctx.getCurrentDeployedApplication().getEnvironment().getName()"
