kind: Rules
metadata:
  namespace: Kubernetes
spec:
  - name: "Kubernetes.StandardJavaSvcProd"
    description: "Standard configuration for Java FE application in K8s PROD"
    condition:
      deployedType: k8s.Resources
      expression: "@k8s.isDeployment"
    processor:
      - type: patch
        description: "Changing replicas to 3 and setting resource limits"
        phase: POST_FLIGHT
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/replicas"
              value: 2"
