kind: Rules
metadata:
  namespace: Kubernetes-Demo
spec:
  - name: "k8s.AddFreemarkerLabels"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment'"
    processor:
      - type: freemarker
        description: "Adding label to kubernetes spec"
        parameters:
          template: |
            { "metadata" : {
               "labels": {
                 "application": "name"
               }
              }
            }
      - type: freemarker
        description: "Adding app and env label"
        parameters:
          templateFile: macro/label-template.ftl
