kind: Rules
metadata:
  namespace: Kubernetes-Demo
spec:
  - name: "k8s.StandardJavaSvcProd"
    description: "Standard configuration for Java FE application in K8s PROD"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment' && #ctx.deployedApplication != null && #ctx.deployedApplication.environment.name == 'rancher-test-test'"
    processor:
      - type: patch
        description: "Changing replicas to 3 and setting resource limits"
        phase: POST_FLIGHT
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/replicas"
              value: 2
      - type: freemarker
        description: "Add CPU and Memory Limits"
        phase: POST_FLIGHT
        merge:
          path: "$.spec.template.spec.containers[0]"
          type: jsonpath
        parameters:
          template: { "resources" : {"limits" : { "cpu" : 2, "memory" : "2048Mi" } } }
