kind: Rules
metadata:
  namespace: Kubernetes
spec:
  - name: "Kubernetes.StandardJavaSvcProd"
    description: "Standard configuration for Java FE application in K8s PROD"
    condition:
      deployedType: k8s.Resources
      expression: "@k8s.isDeployment"
    processor:
      - type: "Kubernetes:ReplicasSizeMacro"
        description: "Change replicas size to dictionary sizes"
        phase: PATCH
        parameters:
          replicasSize: "#{@dictionary.getValue('replicasSize')}"
      - type: "Kubernetes:CpuMemoryLimitsMacro"
        description: "Add CPU and Memory Limits for production"
        phase: PATCH
        parameters:
          cpuNumber: "#{@dictionary.getValue('cpuNumber')}"
          memorySize: "#{@dictionary.getValue('memorySize')}"
